kind: Pod
apiVersion: v1
metadata:
  name: probe-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    readinessProbe:
      periodSeconds: 10
      initialDelaySeconds: 5
      tcpSocket:
        port: 80
    livenessProbe:
      periodSeconds: 20
      initialDelaySeconds: 20
      tcpSocket:
        port: 80
