kind: Pod
apiVersion: v1
metadata:
  name: probe-pod
spec:
  containers:
  - name: secretbox
    image: busybox
    command:
      - sleep
      - "3600"
    readinessProbe:
      periodSeconds: 10
      exec:
        command:
          - cat
          - /tmp/nothing
    resources: {}
