kind: Pod
apiVersion: v1
metadata:
  name: secret-pod
spec:
  containers:
  - name: secretbox
    image: busybox
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: secret
      mountPath: /secretstuff
  volumes:
  - name: secret
    secret:
      secretName: my-new-secret
