kind: Pod
apiVersion: v1
metadata:
  name: secret-pod
spec:
  containers:
  - name: secretbox
    image: busybox
    command:
      - sleep
      - "3600"
    env:
    - name: APP_USERNAME
      valueFrom:
        secretKeyRef:
          name: my-new-secret
          key: user
    - name: APP_PASSWORD
      valueFrom:
        secretKeyRef:
          name: my-new-secret
          key: password
