kind: Role
apiVersion: rbac.authrization.k8s.io/v1beta1
metadata:
  namespace: staff
  name: staff
rules:
- apiGroup: ["", "extensions", "apps"]
  resources: ["deployments", "replicasets", "pods"]
  verbs: ["list", "get", "watch", "create", "update", "patch", "delete"]
