apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  namespace: ckad-ns2
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: alpine
      command:
        - sleep
        - "3600"
      envFrom:
      - configMapRef:
          name: my-config
