apiVersion: v1
kind: Pod
metadata:
  name: sidecar-pod
  namespace: ckad-ns3
spec:

  restartPolicy: Never

  volumes:
  - name: shared-data
    hostPath:
      path: /var/log

  containers:

  - name: alpine
    image: alpine
    command: ["sleep", "3600"]
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: shared-data
      mountPath: /var/log

  - name: busybox-container
    image: busybox
    volumeMounts:
    - name: shared-data
      mountPath: /var/log
    command: ["/bin/sh"]
    args: ["-c", "while true; do date >> /var/log/date.log; sleep 5; done"]
