apiVersion: v1
kind: Pod
metadata:
  name: static-web
  namespace: ckad-ns3
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: httpd
      ports:
      - containerPort: 80
        name: http
      readinessProbe:
        initialDelaySeconds: 60
        exec:
          command: ["ls", "/"]
        periodSeconds: 60
      livenessProbe:
        initialDelaySeconds: 60
        exec:
          command: ["ls", "/"]
        periodSeconds: 60
