apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: webshop
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webshop
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webshop
        service: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.8
        ports:
        - containerPort: 80
