apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1311-pv
  namespace: ckad-1311
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  storageClassName: manual
  hostPath:
    path: "/mnt/data"
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 1311-pvc
  namespace: ckad-1311
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Pod
metadata:
  name: 1311-pod
  namespace: ckad-1311
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
        claimName: 1311-pvc
  containers:
    - name: task-pv-container
      image: nginx:1.8
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/webdata"
          name: task-pv-storage
