apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
  labels:
    app: demo
spec:
  containers:
  - name: demo-container
    image: busybox:1.28.4
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
